# Generated by Django 3.2.23 on 2024-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medscan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdetail',
            old_name='pcv',
            new_name='mch',
        ),
    ]
