# Generated by Django 3.2.23 on 2024-03-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medscan', '0004_auto_20240313_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hemoglobin', models.CharField(blank=True, max_length=100, null=True)),
                ('rbc', models.CharField(blank=True, max_length=100, null=True)),
                ('mch', models.CharField(blank=True, max_length=100, null=True)),
                ('mcv', models.CharField(blank=True, max_length=100, null=True)),
                ('bilirubin_total', models.CharField(blank=True, max_length=100, null=True)),
                ('bilirubin_direct', models.CharField(blank=True, max_length=100, null=True)),
                ('bilirubin_indirect', models.CharField(blank=True, max_length=100, null=True)),
                ('protien', models.CharField(blank=True, max_length=100, null=True)),
                ('urea', models.CharField(blank=True, max_length=100, null=True)),
                ('uric_acid', models.CharField(blank=True, max_length=100, null=True)),
                ('sodium', models.CharField(blank=True, max_length=100, null=True)),
                ('pottasium', models.CharField(blank=True, max_length=100, null=True)),
                ('chloride', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medscan.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
